Add get-orig-source rule to build upstream tarball from github repository

diff --git a/distros/debian/rules b/distros/debian/rules
--- a/distros/debian/rules
+++ b/distros/debian/rules
@@ -1,6 +1,86 @@
 #!/usr/bin/make -f
+# -*- makefile -*-
+# Sample debian/rules that uses debhelper.
 
-DH_VERBOSE=1
+# Uncomment this to turn on verbose mode.
+#export DH_VERBOSE=1
+
+# These are used for cross-compiling and for saving the configure script
+# from having to guess our platform (since we know it already)
+DEB_HOST_GNU_TYPE   ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
+DEB_BUILD_GNU_TYPE  ?= $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
+
+CFLAGS = -Wall
+CPPFLAGS = -D__STDC_CONSTANT_MACROS
+CXXFLAGS = -DHAVE_LIBCRYPTO
+
+ifneq (,$(findstring debug,$(DEB_BUILD_OPTIONS)))
+DEBOPT = --enable-debug
+CFLAGS += -g
+CXXFLAGS += -g
+else
+DEBOPT =
+endif
+
+ifneq (,$(findstring noopt,$(DEB_BUILD_OPTIONS)))
+CFLAGS += -O0
+else
+CFLAGS += -O2
+endif
+
+# These are used to get the most recent version of the original sources from github
+UURL = $(shell git config --get remote.origin.url)
+BRANCH = $(shell git rev-parse --abbrev-ref HEAD)
+HEAD = $(shell git rev-parse HEAD)
+PKD  = $(abspath $(dir $(MAKEFILE_LIST)))
+PKG  = $(word 2,$(shell dpkg-parsechangelog -l$(PKD)/changelog | grep ^Source))
+VER ?= $(shell dpkg-parsechangelog -l$(PKD)/changelog | perl -ne 'print $$1 if m{^Version:\s+(?:\d+:)?(\d.*)(?:\-\d+.*)};')
+DTYPE =
+TARBALL = ../$(PKG)_$(VER)$(DTYPE).orig.tar.xz
 
 %:
-	dh $@ --with quilt,autoreconf --parallel
+	dh $@ --with quilt,autoreconf
+
+.PHONY: override_dh_strip
+override_dh_strip:
+	dh_strip --dbg-package=libzm-plugin-openalpr-dbg
+
+# Inspired by https://wiki.debian.org/onlyjob/get-orig-source
+.PHONY: get-orig-source
+get-orig-source: $(TARBALL) $(info I: $(PKG)_$(VER)$(DTYPE))
+	@
+
+$(TARBALL):
+	$(if $(wildcard $(PKG)-$(VER)),$(error folder '$(PKG)-$(VER)' exists, aborting...))
+	@echo "# Cloning origin repository..."; \
+	if ! git clone $(UURL) $(PKG)-$(VER); then \
+	  $(RM) -r $(PKG)-$(VER); \
+	  echo "failed to clone repository, aborting..."; \
+	  false; \
+	fi
+	@if [ $(BRANCH) != "master" ]; then \
+	  cd $(PKG)-$(VER); \
+	  echo "# Not on master branch, fetching origin branch '$(BRANCH)'..."; \
+	  git fetch origin $(BRANCH):$(BRANCH) || false; \
+	  echo "# Switching to branch '$(BRANCH)'..."; \
+	  git checkout $(BRANCH) || false; \
+	fi
+	@echo "# Checking local source..."
+	@if [ $$(cd $(PKG)-$(VER) && git rev-parse HEAD) = $(HEAD) ]; then \
+	  echo "even with origin, ok"; \
+	  true; \
+	else \
+	  echo "not even with origin, aborting..."; \
+	  false; \
+	fi
+	@echo "# Setting times..."
+	@cd $(PKG)-$(VER) \
+	&& for F in $$(git ls-tree -r --name-only HEAD | sed -e "s/\s/\*/g"); do \
+	  touch --no-dereference -d "$$(git log -1 --format="%ai" -- $$F)" "$$F"; \
+	done
+	@echo "# Cleaning-up..."
+	cd $(PKG)-$(VER) && $(RM) -r .git
+	@echo "# Packing file '$(TARBALL)'..."
+	@find -L "$(PKG)-$(VER)" -xdev -type f -print | sort \
+	| XZ_OPT="-6v" tar -caf "$(TARBALL)" -T- --owner=root --group=root --mode=a+rX \
+	&& $(RM) -r "$(PKG)-$(VER)"
